name: cornetas_itaipu
description: "Aplicativo para acionamento de cornetas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http_auth: ^1.0.4
  # shared_preferences: ^2.5.2
  sqlite3: ^2.7.5
  flex_color_scheme: ^8.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/